# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CrottoGame' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CrottoGame

  target 'CrottoGame-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CrottoGameTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'CrottoGame-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CrottoGame-tvOS

  target 'CrottoGame-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
